### ISSUE TITLE
Changes in version 2.0? 

### ISSUE THREAD

**Issue by ohdongha** [TulsaBioinformaticsToolsmith/Red#6]
Hello, @hani-girgis, 
Thanks for this amazing tool.  I downloaded a binary file from this site: http://toolsmith.ens.utulsa.edu/, and it was fast and appeared to mask repeats well.  

Now I realize that this GitHub page has version 2.0, dated 2018 (the binary from the above site was "Version: 05/22/2015").  Could you let us know what was changed in version 2.0 (e.g. in the release note)?

Cheers, 
Dong-Ha

**Comment by hani-girgis** [comment]
Hi, Dong-Ha.

Thanks for your interest in Red. 

Red v2.0 is even faster. The only difference is that threads are enabled in v2.0.

Best regards.

Hani Z. Girgis, PhD
